# Generated by Django 5.0.6 on 2024-06-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_carbooking_numb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='numb',
        ),
    ]
