# Generated by Django 5.0.6 on 2024-06-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_remove_carbooking_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='numb',
            field=models.IntegerField(default=0),
        ),
    ]
