# Generated by Django 5.0.6 on 2024-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_tourbooking_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='numb',
            field=models.IntegerField(default=0),
        ),
    ]
