# Generated by Django 5.0.6 on 2024-06-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_carbooking_numb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='numb',
            new_name='srno',
        ),
    ]
