# Generated by Django 5.0.6 on 2024-06-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_numb_carbooking_srno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='numb',
            new_name='srno',
        ),
    ]
