# Generated by Django 5.0.6 on 2024-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_rename_numb_tourbooking_srno'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='srno',
            field=models.IntegerField(default=0),
        ),
    ]
